dist: trusty
sudo: required
language: c
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq   - build-essential libx11-dev cmake flex bison ctags clang
compiler:
  - clang
  - gcc
# safelist
branches:
  only:
  - jeanlego
script: make && make install
  
